#!/usr/bin/env python
import boto

conn = boto.connect_ec2()
#get the instance id for this instance
myInstanceId = boto.utils.get_instance_metadata()['instance-id']
ip='127.0.0.1'

#associate public ip

#check if ip available
addrs = conn.get_all_addresses()
for a in addrs:
    if (ip == a.public_ip):
        conn.associate_address(myInstanceId,ip)
